
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, set the GCLOUD_PROJECT environment variable
// in your .env file, then re-start the development server.
import type { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyAHRqi6FiM0jjMIqX0j7Jwj91s0JLyAKak",
  authDomain: "studio-4431476254-c1156.firebaseapp.com",
  projectId: "studio-4431476254-c1156",
  storageBucket: "studio-4431476254-c1156.appspot.com",
  messagingSenderId: "23513776021",
  appId: "1:23513776021:web:3e5b6870112641c0fac09c"
};
